Adventure_Works:
  drivername: sqlserver
  dbname: AdventureWorks2022
  host: LAPTOP-3HKBS1ST\SQLEXPRESS
  trusted_connection: yes
  driver: ODBC Driver 17 for SQL Server

ETL_PRO:
  drivername: postgresql
  dbname: adventureworks_dw
  user: postgres
  password: postgres
  host: localhost
  port: 5432

LOAD_DIMENSIONS: true
START_DATE: '2011-01-01'